# Generated by Django 5.2.13 on 2026-05-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL identifier — must match the slug used in pages/urls.py (e.g. 'home', 'tracyarm2025').", unique=True)),
                ('title', models.CharField(help_text='Used as both the browser tab title and the page heading.', max_length=200)),
                ('body', models.TextField(blank=True, help_text='HTML allowed. Renders inside the page body.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
