# Generated by Django 5.2.14 on 2026-06-07 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QmsLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qms_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tile_url', models.TextField()),
                ('epsg', models.IntegerField(blank=True, null=True)),
                ('scheme', models.CharField(default='xyz', max_length=8)),
                ('z_min', models.IntegerField(default=0)),
                ('z_max', models.IntegerField(default=19)),
                ('attribution', models.TextField(blank=True, default='')),
                ('public', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QMS basemap layer',
                'verbose_name_plural': 'QMS basemap layers',
                'ordering': ['name'],
            },
        ),
    ]
