# Generated by Django 5.2.15 on 2026-07-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_qmslayer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original', models.FileField(upload_to='trace_rasters/originals/')),
                ('image_date', models.DateField(blank=True, help_text='When the imagery was captured — evidence for date bracketing.', null=True)),
                ('source_note', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('error', 'error')], default='processing', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('bounds_w', models.FloatField(blank=True, null=True)),
                ('bounds_s', models.FloatField(blank=True, null=True)),
                ('bounds_e', models.FloatField(blank=True, null=True)),
                ('bounds_n', models.FloatField(blank=True, null=True)),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('tile_count', models.IntegerField(blank=True, null=True)),
                ('tile_bytes', models.BigIntegerField(blank=True, null=True)),
                ('landslide_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trace raster',
                'ordering': ['-created_at'],
            },
        ),
    ]
