# Generated by Django 5.2.17 on 2026-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_traceraster_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceraster',
            name='public',
            field=models.BooleanField(default=False, help_text='Openly licensed and derived, so the tiles may be served to anyone. Uploads stay editor-only.'),
        ),
        migrations.AddField(
            model_name='traceraster',
            name='source_ref',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
