# Generated by Django 5.2.17 on 2026-10-07 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_viewers_to_data_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120, unique=True)),
                ('applies_to', models.CharField(choices=[('both', 'both'), ('slow', 'slow'), ('catastrophic', 'catastrophic')], default='both', max_length=12)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('sort_order', models.IntegerField(default=100)),
                ('legacy_column', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'landslide feature (vocabulary)',
                'verbose_name_plural': 'landslide features (vocabulary)',
                'ordering': ['sort_order', 'value'],
            },
        ),
    ]
