# Generated by Django 5.2.17 on 2026-10-05 20:49

import django.db.models.deletion
import django.utils.timezone
import drops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=drops.models.new_slug, max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, help_text='Shown to the uploader above the drop zone — what you want, what to expect.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Uploads refused after this. Blank = no expiry. Viewing is unaffected.', null=True)),
                ('passphrase_hash', models.CharField(blank=True, max_length=128)),
                ('closed', models.BooleanField(default=False, help_text='Refuse further uploads (reversible). Files stay viewable.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=600)),
                ('size', models.BigIntegerField()),
                ('etag', models.CharField(blank=True, max_length=80)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('thumb_key', models.CharField(blank=True, max_length=600)),
                ('thumb_state', models.CharField(choices=[('pending', 'pending'), ('working', 'working'), ('done', 'done'), ('skip', 'not an image'), ('error', 'error')], default='pending', max_length=10)),
                ('thumb_error', models.CharField(blank=True, max_length=300)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drops.drop')),
            ],
            options={
                'ordering': ['path'],
                'indexes': [models.Index(fields=['drop', 'taken_at'], name='drops_dropf_drop_id_f0f3f3_idx')],
                'unique_together': {('drop', 'path')},
            },
        ),
    ]
