# Generated by Django 5.2.14 on 2026-06-26 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The file to host. Uploaded under MEDIA_ROOT/hosted_files/.', upload_to='hosted_files/')),
                ('name', models.CharField(blank=True, help_text='Public URL token: the file is served at /files/<name>. Leave blank to derive it from the uploaded filename.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9._-]+$', 'Use only letters, numbers, dots, dashes and underscores (e.g. survey_2025.kml).')])),
                ('title', models.CharField(blank=True, help_text='Optional human label (admin only — not shown to the public).', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional notes (admin only).')),
                ('inline', models.BooleanField(default=True, help_text='Serve inline so browsers/apps render it directly. Uncheck to force a download (Content-Disposition: attachment).')),
                ('content_type', models.CharField(blank=True, help_text='Override the MIME type. Blank = auto-detect from the name.', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
